Fix conflicts errors
HomeYou-Kenzie-Academy-t15-g4/HomeYou-Kenzie-m3 pull request #46
Opened 2023-03-10 19:50 UTC by GaTimpone

2023-03-10 20:53 UTC, inaciodh approved these changes

2023-03-10 20:54 UTC, inaciodh approved these changes

2023-03-10 20:54 UTC, inaciodh approved these changes

2023-03-12 13:00 UTC, PONGSU requested changes
resolver alguns conflitos e o input utilizado nesse pull era um temporario dentro da house form, ele foi removido e a pull cria ele de novo. o imput pricipal permanece no componente input fora da pasta houseForm

2023-03-12 19:03 UTC, closed without merging